import { Montserrat } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";

const MontserratSans = Montserrat({
  variable: "--font-geist-montserrat",
  weight: ["100", "500", "400", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "VMS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${MontserratSans.variable} antialiased font-montserrat`}
      >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
